### ISSUE TITLE
Tarjetas de Post

### ISSUE THREAD

**Issue by TheWuilladors** [TheWuilladors/botro#5]
Generar nuevos estilos para los post

**Comment by Test-mk1** [comment]
Cambios implementados con este issue: 

Commit ID: [e9e0527da51140d60836b9548f0edbc0f1a6d13a ](https://github.com/TheWuilladors/botro/commit/e9e0527da51140d60836b9548f0edbc0f1a6d13a)
-Nuevos artes
-Nuevos Copys

Commit ID:  [ee718241e563bac6a12c8de81fa83d7f39a5ee21](https://github.com/TheWuilladors/botro/commit/ee718241e563bac6a12c8de81fa83d7f39a5ee21)
-Nuevos estilos 

Commit ID: [a7a18036b2cea9c1cc4a2bd41ba97b2047839597](https://github.com/TheWuilladors/botro/commit/a7a18036b2cea9c1cc4a2bd41ba97b2047839597)
-Nuevos estilos:hover
